/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ArrayField: typeof import('./src/components/DynamicForm/ArrayField.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CanvasFilter: typeof import('./src/components/CanvasFilter/CanvasFilter.vue')['default']
    ColumnSetting: typeof import('./src/components/ProTable/ColumnSetting.vue')['default']
    Contact: typeof import('./src/components/shawllowRef/contact.vue')['default']
    DraggableList: typeof import('./src/components/DraggableList/DraggableList.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm/DynamicForm.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FormField: typeof import('./src/components/DynamicForm/FormField.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfiniteScroll: typeof import('./src/components/VirtualTable/InfiniteScroll.vue')['default']
    KanbanBoard: typeof import('./src/components/DraggableList/KanbanBoard.vue')['default']
    ProTable: typeof import('./src/components/ProTable/ProTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VirtualList: typeof import('./src/components/VirtualTable/VirtualList.vue')['default']
    VirtualListWithInfinite: typeof import('./src/components/VirtualTable/VirtualListWithInfinite.vue')['default']
    VirtualTable: typeof import('./src/components/VirtualTable/VirtualTable.vue')['default']
    VirtualTableWithInfinite: typeof import('./src/components/VirtualTable/VirtualTableWithInfinite.vue')['default']
    WhiteBoard: typeof import('./src/components/WhiteBoard/WhiteBoard.vue')['default']
    Work: typeof import('./src/components/shawllowRef/work.vue')['default']
  }
}
